### ISSUE TITLE
[startupProjectsNames] adds nothing to the title

### ISSUE THREAD

**Issue by ugumba** [mayerwin/vs-customize-window-title#28]
My solution has .NET Framework and ASP.NET Core projects.  Regardless of which project is set as the startup project, nothing gets added to the title string.  VS2017 15.7.6.

The debug output keeps dumping this:

CustomizeVSWindowTitle: ReplaceTag (startupProjectsNames) failed: System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.SolutionClass.Item(Object index)
   at ErwinMayerLabs.RenameVSWindowTitle.Resolvers.StartupProjectNamesResolver.GetStartupProjectNames() in C:\Users\erwin\Dropbox\Projects\GitHub\vs-customize-window-title\CustomizeVSWindowTitle\Resolvers\SolutionResolver.cs:line 47
   at ErwinMayerLabs.RenameVSWindowTitle.Resolvers.StartupProjectNamesResolver.Resolve(AvailableInfo info) in C:\Users\erwin\Dropbox\Projects\GitHub\vs-customize-window-title\CustomizeVSWindowTitle\Resolvers\SolutionResolver.cs:line 29
   at ErwinMayerLabs.RenameVSWindowTitle.CustomizeVSWindowTitle.<>c__DisplayClass53_0.<GetNewTitle>b__0(Match match) in C:\Users\erwin\Dropbox\Projects\GitHub\vs-customize-window-title\CustomizeVSWindowTitle\CustomizeVSWindowTitlePackage.cs:line 479

**Comment by ugumba** [comment]
It seems the tag only supports top-level projects.  The exception occurs if the startup project is in a solution folder.

**Comment by mayerwin** [comment]
Can you post the pattern you are using so I can replicate?

**Comment by mayerwin** [comment]
Thanks, I have fixed this bug in 3.8.1 (6a6df88ae774e431d3160f822b57db23caf8a287) and pushed it to the marketplace.
